const suggestions = [
    "221B Baker Street: The Master Detective Game Game Game Game Game Game ",
    "221B Baker Street: The Master Detective Game Game Game Game Game Game ",
    "221B Baker Street: The Master Detective Game Game Game Game Game Game ",
    "221B Baker Street: The Master Detective Game Game Game Game Game Game ",
    "221B Baker Street: The Master Detective Game Game Game Game Game Game ",
    "221B Baker Street: The Master Detective Game Game Game Game Game Game ",
    "221B Baker Street: The Master Detective Game Game Game Game Game Game ",
    "30 Seconds",
    "About Time",
    "Acquire",
    "Acronymble",
    "Afrikan tähti",
    "Agricola",
    "Air Charter",
    "Aksharit",
    "Aladdin's Dragons",
    "Alhambra",
    "Alias",
    "Amun-Re",
    "Arkham Horror",
    "Articulate!",
    "Auf Achse",
    "Australia",
    "Azul",
    "Bailout! The Game",
    "Balderdash",
    "Barbarossa",
    "Battlestar Galactica",
    "Bezzerwizzer",
    "Blankety Blank",
    "Blood Rage",
    "Bonkers!",
    "Brain Chain",
    "Buccaneer",
    "Camel Up",
    "Candy Land",
    "Can't Stop",
    "Capitol",
    "Carcassonne",
    "Careers",
    "Caribbean",
    "Cartagena",
    "Caylus",
    "Chinese checkers (Sternhalma)",
    "Chowka bhara",
    "Chromino",
    "CirKis",
    "Civilization",
    "Clans",
    "Clue/Cluedo",
    "Codenames",
    "Coin Hopping—Washington D.C.",
    "Colt Express",
    "Concept",
    "Conspiracy",
    "Continuo",
    "Cosmic Encounter",
    "Catan (The Settlers of Catan)",
    "Cranium",
    "Crosstrack",
    "Dark Tower",
    "Dead of Winter: A Cross Roads Game",
    "Diamant",
    "Dixit",
    "Dominion",
    "Don't Miss the Boat",
    "Don't Quote Me",
    "Dorn",
    "Drunter und Drüber",
    "Dune",
    "Dungeons & Dragons",
    "El Grande",
    "Elfenland",
    "Enchanted Forest",
    "Entdecker",
    "Everdell",
    "Escape from Atlantis",
    "A Feast for Odin",
    "Fictionary",
    "Figure It Out",
    "Fireball Island",
    "Focus",
    "Fresco",
    "Game For Fame",
    "The Game of Life",
    "Gift Trap",
    "Giganten",
    "Girl Talk",
    "The Great Train Robbery",
    "GridIron Master",
    "Halma",
    "History of the World",
    "Hoity Toity",
    "Hooop!",
    "Hūsker Dū?",
    "I'm the Boss!",
    "Imperial",
    "Indigo",
    "Ingenious",
    "Inkan aarre",
    "Java",
    "Journey Through Europe",
    "Junta",
    "Karuba",
    "Keltis",
    "Kill Doctor Lucky",
    "Kingdomino",
    "Kingdoms",
    "Kivi",
    "Labyrinth",
    "Landslide",
    "Las Vegas",
    "Le Havre",
    "The LOGO Board Game",
    "The London Game",
    "Lords of Waterdeep",
    "Löwenherz",
    "Luck of the Draw",
    "Die Macher",
    "The Mad Magazine Game",
    "The Magic Labyrinth",
    "Mahjong",
    "Malefiz",
    "Mall Madness",
    "Manhattan",
    "Masterpiece",
    "Medici",
    "Medina",
    "Mensch ärgere Dich nicht",
    "Merchant of Venus",
    "Metro",
    "Mexica",
    "Mine a Million",
    "Modern Art",
    "Mutant Meeples",
    "Near and Far",
    "Niagara",
    "Okey",
    "Omega Virus",
    "Ouija",
    "Outrage!",
    "Pack & Stack",
    "Pank-a-Squith",
    "Parcheesi",
    "Parqués",
    "Pay Day",
    "Personal Preference",
    "Pictionary",
    "Pirate's Cove",
    "Power Grid",
    "Primordial Soup",
    "The Princes of Florence",
    "Probe",
    "Puerto Rico",
    "Puzzle",
    "Qin",
    "The Quest of the Philosopher's Stone",
    "Quoridor",
    "Qwirkle",
    "Ra",
    "Rail Baron",
    "Railway Rivals",
    "Ricochet Robots",
    "Rivers, Roads & Rails",
    "RoboRally",
    "Rummikub",
    "Rummoli",
    "Saint Petersburg",
    "Samurai",
    "San Marco",
    "Scattergories",
    "Scene It?",
    "Scotland Yard",
    "Scoundrels of Skullport",
    "Scrabble",
    "Scythe",
    "Sequence",
    "Shadows over Camelot",
    "Sherlock Holmes: Consulting Detective",
    "Skirrid",
    "Small World",
    "Snakes and Ladders",
    "Sorry!",
    "Splendor",
    "Squatter",
    "Stock Ticker",
    "Taj Mahal",
    "Take It Easy",
    "Take Off!",
    "Take the Galaxy",
    "Terraforming Mars",
    "Terra Mystica",
    "Through the Ages: A Story of Civilization",
    "Through the Desert",
    "Thurn and Taxis",
    "Ticket to Ride",
    "Tigris and Euphrates",
    "Tikal",
    "Timberland",
    "Time's Up!",
    "Top Secret Spies",
    "Torres",
    "Totopoly",
    "Tracks to Telluride",
    "TransAmerica",
    "Travel Go",
    "Trivial Pursuit",
    "Trouble",
    "Twilight Imperium",
    "Twin Tin Bots",
    "Ubongo",
    "Upwords",
    "Vanished Planet",
    "Vinci",
    "Wingspan",
    "Yahtzee",
    "Yut",
    "Zombies!"
];